In [1]:
import warnings
import pandas as pd

from Connection import Connection
from Extract import Extract
from Transform import Transform

warnings.simplefilter(action = 'ignore', category = FutureWarning)

#### Extracting a CSV file from kaggle

In [2]:
e = Extract()
e.download_kaggle_dataset(
    user = "lewisduncan93/the-economic-freedom-index",
    file_name = "economic_freedom_index2019_data.csv"
)

csv_path_and_file_name = './kaggle_datasets/economic_freedom_index2019_data.csv'

economic_freedom = e.create_df_using_csv(
    csv_path_and_file_name = csv_path_and_file_name,
    separator = ','
)

economic_freedom.head()

Instance of extract object

Used encoding: latin_1

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
1,2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,...,Albania,2.9,$36.0,3.9,2.5,"$12,507",13.9,2.0,"1,119.1",71.2
2,3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,...,Algeria,41.5,$632.9,2.0,3.1,"$15,237",10.0,5.6,"1,203.0",25.8
3,4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,...,Angola,28.2,$190.3,0.7,2.9,"$6,753",8.2,31.7,"-2,254.5",65.3
4,5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,...,Argentina,44.1,$920.2,2.9,0.7,"$20,876",8.7,25.7,"11,857.0",52.6

#### Transforming columns

##### As we can see below, there are many fields that need to be converted in float type.

In [3]:
economic_freedom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CountryID                    186 non-null    int64
 1   Country Name                 186 non-null    object
 2   WEBNAME                      186 non-null    object
 3   Region                       186 non-null    object
 4   World Rank                   180 non-null    float64
 5   Region Rank                  180 non-null    float64
 6   2019 Score                   180 non-null    float64
 7   Property Rights              185 non-null    float64
 8   Judical Effectiveness        185 non-null    float64
 9   Government Integrity         185 non-null    float64
 10  Tax Burden                   180 non-null    float64
 11  Gov't Spending               183 non-null    float64
 12  Fiscal Health                183 non-null    float64
 13  Business Freedom             185 non-null    float64
 14  Labor Freedom                184 non-null    float64
 15  Monetary Freedom             184 non-null    float64
 16  Trade Freedom                182 non-null    float64
 17  Investment Freedom           184 non-null    float64
 18  Financial Freedom            181 non-null    float64
 19  Tariff Rate (%)              182 non-null    float64
 20  Income Tax Rate (%)          183 non-null    float64
 21  Corporate Tax Rate (%)       183 non-null    float64
 22  Tax Burden % of GDP          179 non-null    float64
 23  Gov't Expenditure % of GDP   182 non-null    float64
 24  Country                      186 non-null    object
 25  Population (Millions)        186 non-null    object
 26  GDP (Billions, PPP)          185 non-null    object
 27  GDP Growth Rate (%)          184 non-null    float64
 28  5 Year GDP Growth Rate (%)   183 non-null    float64
 29  GDP per Capita (PPP)         184 non-null    object
 30  Unemployment (%)             181 non-null    object
 31  Inflation (%)                182 non-null    float64
 32  FDI Inflow (Millions)        181 non-null    object
 33  Public Debt (% of GDP)       182 non-null    float64
dtypes: float64(24), int64(1), object(9)
memory usage: 49.5+ KB

In [4]:
t = Transform()
columns_to_convert_float = [
    'Population (Millions)', 
    'GDP (Billions, PPP)', 
    'GDP per Capita (PPP)', 
    'Unemployment (%)',
    'FDI Inflow (Millions)',
    'Tax Burden % of GDP'
]

economic_freedom = t.transform_columns_type(
    df = economic_freedom,
    columns = columns_to_convert_float,
    target_type = 'float'
)

economic_freedom[
   columns_to_convert_float
].info(columns_to_convert_float)

Instance of transform object

The column named: Tax Burden % of GDP don't contains non-numeric character.
Column: Population (Millions) transformed in float type.
Column: GDP (Billions, PPP) transformed in float type.
Column: GDP per Capita (PPP) transformed in float type.
Column: Unemployment (%) transformed in float type.
Column: FDI Inflow (Millions) transformed in float type.
Column: Tax Burden % of GDP transformed in float type.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Population (Millions)  186 non-null    float64
 1   GDP (Billions, PPP)    185 non-null    float64
 2   GDP per Capita (PPP)   184 non-null    float64
 3   Unemployment (%)       181 non-null    float64
 4   FDI Inflow (Millions)  181 non-null    float64
 5   Tax Burden % of GDP    179 non-null    float64
dtypes: float64(6)
memory usage: 8.8 KB

##### Deleting NaN values.

In [5]:
rows_contains_null_fields = t.show_where_is_null(
    df = economic_freedom,
    columns = columns_to_convert_float
)

rows_contains_null_fields[[
    'Population (Millions)', 
    'GDP (Billions, PPP)', 
    'GDP per Capita (PPP)', 
    'Unemployment (%)',
    'FDI Inflow (Millions)',
    'Tax Burden % of GDP'
]]

,Population (Millions),"GDP (Billions, PPP)",GDP per Capita (PPP),Unemployment (%),FDI Inflow (Millions),Tax Burden % of GDP
78,38.0,658.0,16.0,8.0,5.0,NaN
88,25.0,40.0,1.0,4.0,63.0,NaN
98,6.0,64.0,9.0,17.0,NaN,NaN
99,38.0,6.0,139.0,2.0,NaN,NaN
153,14.0,18.0,NaN,6.0,384.0,NaN
161,18.0,NaN,NaN,14.0,NaN,NaN
183,30.0,38.0,1.0,14.0,269.0,NaN

In [6]:
print(f"Before delete: {economic_freedom.shape}")

economic_freedom = t.delete_where_is_null_using_index(
    df = economic_freedom, 
    df_rows_to_exclude = rows_contains_null_fields)

print(f"After delete: {economic_freedom.shape}")

Before delete: (186, 34)
After delete: (179, 34)

#### Filtering data using a column as criteria.

In [7]:
df_brazil = t.filter_data(
    df = economic_freedom,
    column = 'Region',
    criteria = 'Americas'
)

df_brazil.head(15)

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,...,Argentina,44.0,920.0,2.9,0.7,20.0,8.0,25.7,11.0,52.6
1,10,Bahamas,Bahamas,Americas,76.0,15.0,62.9,42.2,46.9,43.7,...,Bahamas,0.0,11.0,1.3,-0.7,31.0,12.0,1.4,927.0,57.2
2,13,Barbados,Barbados,Americas,67.0,13.0,64.7,52.9,59.9,53.8,...,Barbados,0.0,5.0,0.9,0.6,18.0,9.0,4.4,286.0,132.9
3,16,Belize,Belize,Americas,123.0,24.0,55.4,41.7,46.9,27.2,...,Belize,0.0,3.0,0.8,1.8,8.0,9.0,1.1,77.0,99.0
4,19,Bolivia,Bolivia,Americas,173.0,30.0,42.3,20.5,12.3,19.7,...,Bolivia,11.0,83.0,4.2,5.1,7.0,3.0,2.8,724.0,50.9
5,22,Brazil,Brazil,Americas,150.0,27.0,51.9,57.3,51.7,28.1,...,Brazil,207.0,3.0,1.0,-0.5,15.0,13.0,3.4,62.0,84.0
6,29,Canada,Canada,Americas,8.0,1.0,77.7,87.0,69.4,84.6,...,Canada,36.0,1.0,3.0,2.1,48.0,6.0,1.6,24.0,89.7
7,33,Chile,Chile,Americas,18.0,3.0,75.4,68.7,56.3,62.3,...,Chile,18.0,451.0,1.5,2.2,24.0,7.0,2.2,6.0,23.6
8,35,Colombia,Colombia,Americas,49.0,8.0,67.3,59.2,34.3,33.5,...,Colombia,49.0,714.0,1.8,3.2,14.0,8.0,4.3,14.0,49.4
9,39,Costa Rica,CostaRica,Americas,61.0,11.0,65.3,58.3,54.0,54.5,...,Costa Rica,5.0,83.0,3.2,3.4,16.0,8.0,1.6,3.0,49.1
10,42,Cuba,Cuba,Americas,178.0,31.0,27.8,31.6,10.0,37.7,...,Cuba,11.0,148.0,0.9,1.9,12.0,2.0,5.5,NaN,47.7
11,47,Dominica,Dominica,Americas,72.0,14.0,63.6,49.2,63.8,54.5,...,Dominica,0.0,0.0,-4.2,0.0,11.0,NaN,0.6,18.0,87.6
12,48,Dominican Republic,DominicanRepublic,Americas,89.0,19.0,61.0,50.6,18.1,23.2,...,Dominican Republic,10.0,172.0,4.6,6.1,16.0,5.0,3.3,3.0,37.7
13,49,Ecuador,Ecuador,Americas,170.0,29.0,46.9,35.9,20.2,25.3,...,Ecuador,16.0,192.0,2.7,2.0,11.0,3.0,0.4,606.0,45.0
14,51,El Salvador,ElSalvador,Americas,84.0,17.0,61.8,37.6,29.1,23.4,...,El Salvador,6.0,57.0,2.4,2.1,8.0,4.0,1.0,791.0,59.3

#### Saving transformed data in csv files

In [9]:
e.create_csv_using_df(
    df = economic_freedom,
    folder_name = 'transformed_datasets',
    target_file_name = 'economic_freedom_transformed'
)

"CSV file created in './transformed_datasets/economic_freedom_transformed.csv'"